### ISSUE TITLE
Google auth fails with disallowed_useragent on Android

### ISSUE THREAD

**Issue by romandrahan** [PeterStaev/nativescript-azure-mobile-apps#32]
Google auth fails with `disallowed_useragent` on Android: http://take.ms/BLLFD. While it works perfectly on iOS.

I've tried adding intent filter to the `AndroidManifest.xml` with no luck:

```
<intent-filter>
    <action android:name="android.intent.action.VIEW" />

    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />

    <data android:scheme="x-msauth-tns-azure-sample" android:host="easyauth.callback" />
</intent-filter>
```

As mentioned [here](https://github.com/Azure/azure-mobile-apps-android-client/blob/master/CHANGELOG.md#android-sdk-version-320) we need to use updated `MobileServiceClient.login` method, that now also accepts `uriScheme` and `authRequestCode`.

So looks like [this](https://github.com/PeterStaev/nativescript-azure-mobile-apps/blob/master/client/client.android.ts#L63) line have to be updated.

**Comment by romandrahan** [comment]
cc @PeterStaev

**Comment by PeterStaev** [comment]
@romandragan , since I'm the owner the of repo there is no need to CC me...

From what I see seems Azure does not provide a good workaround for this case (like they have built int for iOS) and it is suggested to use browser login and then pass the received token to the login method directly, instead of using the current workflow. 

I'll mark this as an enhancement but I do not have any ETA/fix that I can share at the moment.
